name: example-environment
channels:
  - conda-forge
dependencies:
  - numpy
  - psutil
  - toolz
  - matplotlib
  - dill
  - pandas
  - partd
  - scipy
  - dask
  - thinc
  - seaborn
  - tqdm
  - sklearn
  - pillow
  - xgboost
  - requests
  - lightgbm
  - catboost
  - pyproj
  - scrapy
  - pyecharts
  - bokeh
  - altair
  - geopandas
  - jupyter_contrib_nbextensions
  - tensorflow
  - opencv-python
  - ggplot
  - folium
  - fiona
  - cutecharts
  - plotly
  - xlrd
  - geoplotlib
  - cufflinks
  - basemap
