name: example-environment
channels:
  - conda-forge
dependencies:
  - numpy
  - psutil
  - toolz
  - matplotlib
  - dill
  - pandas
  - partd
  - scipy
  - dask
  - thinc
  - seaborn
  - tqdm
  - requests
  - bokeh
  - altair
  - geopandas
  - plotly
  - ggplot
  - fiona
 
  
  
